// <auto-generated />
using MainLogic.AppDataManip;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MainLogic.AppDataManip.Migrations
{
    [DbContext(typeof(AppDataDbContext))]
    partial class AppDataDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.6");

            modelBuilder.Entity("Entities.Heroes.HeroBaseEntity", b =>
                {
                    b.Property<int>("SaveSlot")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("DefencePercentage")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("DefenseIncreasePerLevel")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Dmg")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("DmgPerLevel")
                        .HasColumnType("TEXT");

                    b.Property<string>("HeroType")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Hp")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("HpPerLevel")
                        .HasColumnType("TEXT");

                    b.Property<int>("Level")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("MaxDefense")
                        .HasColumnType("TEXT");

                    b.Property<int>("Money")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Mp")
                        .HasColumnType("TEXT");

                    b.Property<int>("TurnCounter")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Xp")
                        .HasColumnType("TEXT");

                    b.HasKey("SaveSlot");

                    b.ToTable("Heroes");

                    b.HasDiscriminator<string>("HeroType").HasValue("HeroBaseEntity");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Entities.Items.Item", b =>
                {
                    b.Property<int>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Price")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SaveSlot")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("ItemId");

                    b.ToTable("ShopItems");
                });

            modelBuilder.Entity("Entities.Items.OwnedItemsBase", b =>
                {
                    b.Property<int>("SaveSlot")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Archer_ArmorOfTheElves")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Archer_BootsOfTheElves")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Archer_BowOfTheElves")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Archer_Crossbow")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Archer_HunterArmor")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Archer_LongBow")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Archer_QuickBow")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Archer_SneakingBoots")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Archer_TraineeArmor")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Common_BigHealingPotion")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Common_BigManaPotion")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Common_BlessingOfLife")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Common_BlessingOfTheMagician")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Common_KaitoKey")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Common_SmallHealingPotion")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Common_SmallManaPotion")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Mage_CharmOfTheWind")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Mage_ManaAmulet")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Mage_OrbOfTheArchmage")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Mage_SpellBook")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Mage_StaffOfTheArchmage")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Mage_StaffOfTheRoyalWizard")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Mage_WizardStaff")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Mage_WoodenStaff")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Warrior_ArmorOfMarcus")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Warrior_ChainMailArmor")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Warrior_IronShield")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Warrior_IronSword")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Warrior_LeatherArmor")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Warrior_PlateArmor")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Warrior_ShieldOfMarcus")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Warrior_SwordOfMarcus")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Warrior_WoodenShield")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Warrior_WoodenSword")
                        .HasColumnType("INTEGER");

                    b.HasKey("SaveSlot");

                    b.ToTable("OwnedItems");
                });

            modelBuilder.Entity("MainLogic.GlobalParameters.BaseEntities.GameStateParametersBaseEntity", b =>
                {
                    b.Property<int>("SaveSlot")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("DungeonCleared")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EnemyDefeated")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GlobalDungeonsCleared")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GlobalEnemiesKilled")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GlobalTimesDefeated")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDefeated")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("KaitoKeyEffect")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NumberOfEnemiesDefeated")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NumberOfEnemiesPerDungeon")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Saving")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("ScaleFactor")
                        .HasColumnType("TEXT");

                    b.HasKey("SaveSlot");

                    b.ToTable("GameStateParameters");
                });

            modelBuilder.Entity("Entities.Heroes.ArcherEntity", b =>
                {
                    b.HasBaseType("Entities.Heroes.HeroBaseEntity");

                    b.HasDiscriminator().HasValue("Archer");
                });

            modelBuilder.Entity("Entities.Heroes.MageEntity", b =>
                {
                    b.HasBaseType("Entities.Heroes.HeroBaseEntity");

                    b.HasDiscriminator().HasValue("Mage");
                });

            modelBuilder.Entity("Entities.Heroes.WarriorEntity", b =>
                {
                    b.HasBaseType("Entities.Heroes.HeroBaseEntity");

                    b.HasDiscriminator().HasValue("Warrior");
                });
#pragma warning restore 612, 618
        }
    }
}
